name: DB Migration (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pymysql==1.1.1

      - name: Dependency vulnerability scan
        run: |
          pip install pip-audit
          pip-audit

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: app
        run: |
          docker build \
            -t ${{ secrets.ECR_REPOSITORY_DB }}:${IMAGE_TAG} \
            -t ${{ secrets.ECR_REPOSITORY_DB }}:latest .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.ECR_REPOSITORY_DB }}:${{ github.run_number }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_DB }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REPOSITORY_DB }}:latest

      - name: Resolve network configuration dynamically
        run: |
          SG_ID=$(aws ec2 describe-security-groups \
            --filters "Name=tag:Name,Values=genea-ecs-service-sg" \
            --query "SecurityGroups[0].GroupId" \
            --output text)

          SUBNET_IDS=$(aws ec2 describe-subnets \
            --filters "Name=tag:Tier,Values=private" \
            --query "Subnets[*].SubnetId" \
            --output text | tr '\t' ',')

          echo "ECS_SECURITY_GROUP_ID=$SG_ID" >> $GITHUB_ENV
          echo "ECS_SUBNET_IDS=$SUBNET_IDS" >> $GITHUB_ENV


      - name: Run DB Migration Task
        run: |
          aws ecs run-task \
            --cluster ${{ vars.ECS_CLUSTER_NAME }} \
            --launch-type EC2 \
            --task-definition genea-db-migration \
            --network-configuration "awsvpcConfiguration={subnets=[${{ vars.PRIVATE_SUBNET_IDS }}],securityGroups=[${{ vars.ECS_TASK_SG_ID }}],assignPublicIp=DISABLED}" \
            --count 1
